### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by solidgoldpig** [UKHomeOffice/hof-example-form#124]
Checking out from master (00805f828bd73f3fa77005300f59d19d0c36dbc9) I get the following when I `npm install`

```
npm ERR! hmpo-govuk-template@0.0.3 postinstall: `node ./build/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hmpo-govuk-template@0.0.3 postinstall script 'node ./build/index.js'.
npm ERR! This is most likely a problem with the hmpo-govuk-template package,
```

Would love to check it out - but time prevents me from doing anything other than reporting the problem

```
node -v
v4.5.0

npm -v
2.15.9
```

**Comment by solidgoldpig** [comment]
I got things to work by 

```
npm install hmpo-govuk-template@0.0.3
```

which spawned this error

```
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/alexrobinson/Projects/hof-example-form/node_modules/hof/node_modules/hmpo-frontend-toolkit/build:7:13)
```

so

```
npm install async
```

then 

```
npm install
```

finally works

**Comment by solidgoldpig** [comment]
However running the app, and hitting `http://localhost:8080/my-awesome-form`, I get redirected to
`http://localhost:8080/my-awesome-form/first-page` but a session_timeout is all that gets displayed on the page

Definitely connecting to redis

```
{"level":"info","message":"Connected to redis","timestamp":"2016-09-21T15:23:13.558Z"}
```

Logging says this about the session timeout

```
{"code":"SESSION_TIMEOUT","level":"error","timestamp":"2016-09-21T15:23:19.425Z"}
```

Can't see anything in redis at all

**Comment by joefitter** [comment]
there is a bug with this particular module and npm<3. The issue is its trying to run the postinstall build before install has finished.

You can fix by running `npm install || npm install` (hacky) or update npm to >= 3
